# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import actions_pb2 as actions__pb2


class CloudActionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getAction = channel.unary_unary(
        '/actions.CloudActionService/getAction',
        request_serializer=actions__pb2.CloudActionRequest.SerializeToString,
        response_deserializer=actions__pb2.CloudActionResponse.FromString,
        )


class CloudActionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudActionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getAction': grpc.unary_unary_rpc_method_handler(
          servicer.getAction,
          request_deserializer=actions__pb2.CloudActionRequest.FromString,
          response_serializer=actions__pb2.CloudActionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'actions.CloudActionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
