# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getChatResponse = channel.unary_unary(
        '/chat.ChatService/getChatResponse',
        request_serializer=chat__pb2.ChatRequest.SerializeToString,
        response_deserializer=chat__pb2.ChatResponse.FromString,
        )


class ChatServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getChatResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getChatResponse': grpc.unary_unary_rpc_method_handler(
          servicer.getChatResponse,
          request_deserializer=chat__pb2.ChatRequest.FromString,
          response_serializer=chat__pb2.ChatResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chat.ChatService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
